LOCAL_PATH := $(call my-dir)

$(info == Android.mk File ==)

include $(CLEAR_VARS)

# Uncomment the next 2 lines to do debugging with ndk-gdb:
#APP_OPTIM:= debug
#LOCAL_CFLAGS    := -ggdb -O0

LOCAL_MODULE    := tutorial-3
LOCAL_SRC_FILES := tutorial-3.c
LOCAL_SHARED_LIBRARIES := gstreamer_android
LOCAL_LDLIBS := -llog -landroid
include $(BUILD_SHARED_LIBRARY)

TARGET_ARCH_ABI := armeabi
GSTREAMER_ROOT_ANDROID := D:/Android/gst_android_sdk
GSTREAMER_ROOT        := $(GSTREAMER_ROOT_ANDROID)/arm
LOCAL_C_INCLUDES += $(GSTREAMER_ROOT_ANDROID)/arm/includes

GSTREAMER_NDK_BUILD_PATH  := $(GSTREAMER_ROOT)/share/gst-android/ndk-build/
include $(GSTREAMER_NDK_BUILD_PATH)/plugins.mk
GSTREAMER_PLUGINS         := $(GSTREAMER_PLUGINS_CORE) $(GSTREAMER_PLUGINS_PLAYBACK) $(GSTREAMER_PLUGINS_CODECS) $(GSTREAMER_PLUGINS_NET) $(GSTREAMER_PLUGINS_SYS)  $(GSTREAMER_PLUGINS_CODECS_RESTRICTED) $(GSTREAMER_PLUGINS_CODECS_GPL) $(GSTREAMER_PLUGINS_ENCODING) $(GSTREAMER_PLUGINS_VIS) $(GSTREAMER_PLUGINS_EFFECTS) $(GSTREAMER_PLUGINS_NET_RESTRICTED)
GSTREAMER_EXTRA_DEPS      := gstreamer-video-1.0 gio-2.0

include $(GSTREAMER_NDK_BUILD_PATH)/gstreamer-1.0.mk
